### ISSUE TITLE
Error when converting csv to image

### ISSUE THREAD

**Issue by Rabab53** [imodpasteur/ANNA-PALM#30]
Hello great developers, 

I have built my own localization table and I am trying to start the training step. It produces the following error: 
Could you please help in this issue?

Found 5 samples in ./training_workdir_exp1/train.
generating images...
Traceback (most recent call last):
  File "run_csv.py", line 30, in <module>
    sources = create_data_sources('TransformedCSVImages', opt)
  File "/home/omairyrm/ANNA-PALM/smlm_datasets.py", line 47, in create_data_sources
    return TransformedCSVImages(opt)
  File "/home/omairyrm/ANNA-PALM/smlm_datasets.py", line 322, in __init__
    target_size=(2560, 2560))
  File "/home/omairyrm/ANNA-PALM/localization_utils.py", line 395, in generate_image_pairs_from_csv
    (aa, bb, p, inf_range, outf_range) = source_train[i]
  File "/home/omairyrm/ANNA-PALM/AnetLib/data/folder_dataset.py", line 94, in __getitem__
    ret = self.transform(ret.copy())
  File "/home/omairyrm/ANNA-PALM/localization_utils.py", line 373, in transform_train
    tableout = fSamplerOutTest(table, index=repeat)
  File "/home/omairyrm/ANNA-PALM/localization_utils.py", line 195, in __call__
    assert self.frame_limit[0]<self.frame_limit[1]
AssertionError
AssertionError

**Comment by baiddd** [comment]
Hi @Rabab53, 
Sorry for this late reply, It's possible that your acquisition of given samples has less than 2000 frames, you could change [this line](https://github.com/imodpasteur/ANNA-PALM/blob/ef440dfed68fdacdb384a188f3d4d7b854a98f63/smlm_datasets.py#L320) to `B_frame_limit=(0, 1.0),`
